<?php
/**
 * Created by PhpStorm.
 * User: admin
 * Date: 2017/12/21
 * Time: 18:57
 */

namespace backend\controllers;


use backend\components\event\MailEvent;
use yii\web\Controller;

class SendMailController extends Controller
{
    const SEND_MAIL='send_mail';
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->on(self::SEND_MAIL,['backend\components\Mail','sendMail']);
    }

    public function actionIndex(){
        $event=new MailEvent();
        $event->email='136187101@qq.com';
        $event->subject='test email';
        $event->content='tect content';
        $this->trigger(self::SEND_MAIL,$event);
    }

}